set_attack_value(AT_DAIR, AG_CATEGORY, 1);
set_attack_value(AT_DAIR, AG_SPRITE, sprite_get("dair"));
set_attack_value(AT_DAIR, AG_NUM_WINDOWS, 5);
set_attack_value(AT_DAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_DAIR, AG_LANDING_LAG, 9);
set_attack_value(AT_DAIR, AG_HURTBOX_SPRITE, sprite_get("dair_hurt"));

set_window_value(AT_DAIR, 1, AG_WINDOW_LENGTH, 27);
set_window_value(AT_DAIR, 1, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_DAIR, 1, AG_WINDOW_HAS_SFX, 0);

set_window_value(AT_DAIR, 2, AG_WINDOW_LENGTH, 11);
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_DAIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_DAIR, 2, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_DAIR, 3, AG_WINDOW_LENGTH, 11);
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DAIR, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_DAIR, 3, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_DAIR, 4, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_DAIR, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 4, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_DAIR, 4, AG_WINDOW_SFX_FRAME, 7);

set_window_value(AT_DAIR, 5, AG_WINDOW_LENGTH, 20);
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAME_START, 15);
set_window_value(AT_DAIR, 5, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_DAIR, 6);

set_hitbox_value(AT_DAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_DAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR, 1, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DAIR, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_Y, -3);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_X, 9);
set_hitbox_value(AT_DAIR, 1, HG_WIDTH, 110);
set_hitbox_value(AT_DAIR, 1, HG_HEIGHT, 75);
set_hitbox_value(AT_DAIR, 1, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_DAIR, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_DAIR, 1, HG_ANGLE, 75);
set_hitbox_value(AT_DAIR, 1, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_DAIR, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DAIR, 1, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_DAIR, 1, HG_BASE_HITPAUSE, 6.2);
set_hitbox_value(AT_DAIR, 1, HG_HITPAUSE_SCALING, .44);
set_hitbox_value(AT_DAIR, 1, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 1, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, 15);
set_hitbox_value(AT_DAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_DAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_DAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DAIR, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DAIR, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 4, HG_HITBOX_Y, -36);
set_hitbox_value(AT_DAIR, 4, HG_HITBOX_X, 55);
set_hitbox_value(AT_DAIR, 4, HG_WIDTH, 50);
set_hitbox_value(AT_DAIR, 4, HG_HEIGHT, 30);
set_hitbox_value(AT_DAIR, 4, HG_SHAPE, 2);
set_hitbox_value(AT_DAIR, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_DAIR, 4, HG_ANGLE, 60);
set_hitbox_value(AT_DAIR, 4, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DAIR, 4, HG_BASE_KNOCKBACK, 6.4);
set_hitbox_value(AT_DAIR, 4, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_DAIR, 4, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_DAIR, 4, HG_HITPAUSE_SCALING, .44);
set_hitbox_value(AT_DAIR, 4, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 4, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_weak2"));

set_hitbox_value(AT_DAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_DAIR, 2, HG_WINDOW, 3);
set_hitbox_value(AT_DAIR, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DAIR, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_Y, 1);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_X, 4);
set_hitbox_value(AT_DAIR, 2, HG_WIDTH, 110);
set_hitbox_value(AT_DAIR, 2, HG_HEIGHT, 65);
set_hitbox_value(AT_DAIR, 2, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_DAIR, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_DAIR, 2, HG_ANGLE, 75);
set_hitbox_value(AT_DAIR, 2, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_DAIR, 2, HG_BASE_KNOCKBACK, 4.4);
set_hitbox_value(AT_DAIR, 2, HG_KNOCKBACK_SCALING, 0.044);
set_hitbox_value(AT_DAIR, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DAIR, 2, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DAIR, 2, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 2, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 2, HG_VISUAL_EFFECT_Y_OFFSET, 15);
set_hitbox_value(AT_DAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_DAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 5, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_DAIR, 5, HG_WINDOW, 3);
set_hitbox_value(AT_DAIR, 5, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DAIR, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 5, HG_HITBOX_Y, -20);
set_hitbox_value(AT_DAIR, 5, HG_HITBOX_X, 55);
set_hitbox_value(AT_DAIR, 5, HG_WIDTH, 40);
set_hitbox_value(AT_DAIR, 5, HG_HEIGHT, 30);
set_hitbox_value(AT_DAIR, 5, HG_SHAPE, 2);
set_hitbox_value(AT_DAIR, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR, 5, HG_DAMAGE, 2);
set_hitbox_value(AT_DAIR, 5, HG_ANGLE, 60);
set_hitbox_value(AT_DAIR, 5, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DAIR, 5, HG_BASE_KNOCKBACK, 5.8);
set_hitbox_value(AT_DAIR, 5, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_DAIR, 5, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_DAIR, 5, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DAIR, 5, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 5, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_weak2"));

set_hitbox_value(AT_DAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 3, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_DAIR, 3, HG_WINDOW, 4);
set_hitbox_value(AT_DAIR, 3, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_DAIR, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 3, HG_HITBOX_Y, 8);
set_hitbox_value(AT_DAIR, 3, HG_HITBOX_X, 9);
set_hitbox_value(AT_DAIR, 3, HG_WIDTH, 105);
set_hitbox_value(AT_DAIR, 3, HG_HEIGHT, 75);
set_hitbox_value(AT_DAIR, 3, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_DAIR, 3, HG_DAMAGE, 4);
set_hitbox_value(AT_DAIR, 3, HG_ANGLE, 281);
set_hitbox_value(AT_DAIR, 3, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DAIR, 3, HG_BASE_KNOCKBACK, 6.25);
set_hitbox_value(AT_DAIR, 3, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_DAIR, 3, HG_BASE_HITPAUSE, 9.5);
set_hitbox_value(AT_DAIR, 3, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_DAIR, 3, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 3, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 3, HG_VISUAL_EFFECT_Y_OFFSET, 15);
set_hitbox_value(AT_DAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));

set_hitbox_value(AT_DAIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 6, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_DAIR, 6, HG_WINDOW, 4);
set_hitbox_value(AT_DAIR, 6, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_DAIR, 6, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 6, HG_HITBOX_Y, -20);
set_hitbox_value(AT_DAIR, 6, HG_HITBOX_X, 55);
set_hitbox_value(AT_DAIR, 6, HG_WIDTH, 30);
set_hitbox_value(AT_DAIR, 6, HG_HEIGHT, 40);
set_hitbox_value(AT_DAIR, 6, HG_SHAPE, 2);
set_hitbox_value(AT_DAIR, 6, HG_PRIORITY, 1);
set_hitbox_value(AT_DAIR, 6, HG_DAMAGE, 3);
set_hitbox_value(AT_DAIR, 6, HG_ANGLE, 65);
set_hitbox_value(AT_DAIR, 6, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DAIR, 6, HG_BASE_KNOCKBACK, 6.4);
set_hitbox_value(AT_DAIR, 6, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(AT_DAIR, 6, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DAIR, 6, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_DAIR, 6, HG_EXTRA_HITPAUSE, cactus);
set_hitbox_value(AT_DAIR, 6, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_DAIR, 6, HG_HIT_SFX, asset_get("sfx_blow_medium1"));