set_attack_value(AT_FTILT, AG_CATEGORY, 0);
set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));
set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_FTILT, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_FTILT, AG_OFF_LEDGE, 1);
set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));

set_window_value(AT_FTILT, 1, AG_WINDOW_TYPE, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 16);
set_window_value(AT_FTILT, 1, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX, asset_get("sfx_ori_energyhit_weak"));
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX_FRAME, 11);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .30);

set_window_value(AT_FTILT, 2, AG_WINDOW_TYPE, 0);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 15);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .22);

set_window_value(AT_FTILT, 3, AG_WINDOW_TYPE, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 20);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAME_START, 10);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 0);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FTILT, 4);


set_hitbox_value(AT_FTILT, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_FTILT, 4, HG_WINDOW, 1);
set_hitbox_value(AT_FTILT, 4, HG_WINDOW_CREATION_FRAME, 10);
set_hitbox_value(AT_FTILT, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_FTILT, 4, HG_WIDTH, 100);
set_hitbox_value(AT_FTILT, 4, HG_HEIGHT, 70);
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_X, -2);
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_Y, -65);
set_hitbox_value(AT_FTILT, 4, HG_SHAPE, 2);
set_hitbox_value(AT_FTILT, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_FTILT, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_FTILT, 4, HG_ANGLE, 40);
set_hitbox_value(AT_FTILT, 4, HG_BASE_KNOCKBACK, 7.7);
set_hitbox_value(AT_FTILT, 4, HG_KNOCKBACK_SCALING, .05);
set_hitbox_value(AT_FTILT, 4, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_FTILT, 4, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_FTILT, 4, HG_HITSTUN_MULTIPLIER, 1.22);
set_hitbox_value(AT_FTILT, 4, HG_DRIFT_MULTIPLIER, .4);
set_hitbox_value(AT_FTILT, 4, HG_SDI_MULTIPLIER, .8);
set_hitbox_value(AT_FTILT, 4, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_FTILT, 4, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FTILT, 4, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FTILT, 4, HG_TECHABLE, 1);

set_hitbox_value(AT_FTILT, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_FTILT, 3, HG_LIFETIME, 80);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_X,  40);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 3, HG_WIDTH, 25);
set_hitbox_value(AT_FTILT, 3, HG_HEIGHT, 25);
set_hitbox_value(AT_FTILT, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_FTILT, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 3, HG_ANGLE, 60);
set_hitbox_value(AT_FTILT, 3, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_FTILT, 3, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 3, HG_KNOCKBACK_SCALING, 0.35);
set_hitbox_value(AT_FTILT, 3, HG_BASE_HITPAUSE, 6.6);
set_hitbox_value(AT_FTILT, 3, HG_HITPAUSE_SCALING, .6);
set_hitbox_value(AT_FTILT, 3, HG_DRIFT_MULTIPLIER, .9);
set_hitbox_value(AT_FTILT, 3, HG_SDI_MULTIPLIER, .9);
set_hitbox_value(AT_FTILT, 3, HG_HITSTUN_MULTIPLIER, .9);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_SPRITE, sprite_get("star_projectile"));
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FTILT, 3, HG_HIT_SFX, asset_get("sfx_ori_seinhit_medium"));
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_HSPEED, 7.5);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_VSPEED, -.9);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_PLASMA_SAFE, false);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_FTILT, 3, HG_PROJECTILE_DESTROY_EFFECT, starhit);

set_hitbox_value(AT_FTILT, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW_CREATION_FRAME, 10);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 80);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X,  50);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 25);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 25);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 80);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE_FLIPPER, 5);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, 0.035);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 4.4);
set_hitbox_value(AT_FTILT, 2, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_FTILT, 2, HG_DRIFT_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 2, HG_SDI_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 2, HG_HITSTUN_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_SPRITE, sprite_get("star_projectile"));
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_ori_seinhit_medium"));
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_HSPEED, 7.5);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_VSPEED, .88);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_PLASMA_SAFE, false);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_FTILT, 2, HG_PROJECTILE_DESTROY_EFFECT, starhit);

set_hitbox_value(AT_FTILT, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 80);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X,  45);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 25);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 25);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 40);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE_FLIPPER, 5);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 4.4);
set_hitbox_value(AT_FTILT, 1, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_FTILT, 1, HG_DRIFT_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 1, HG_SDI_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 1, HG_HITSTUN_MULTIPLIER, .6);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_SPRITE, sprite_get("star_projectile"));
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_ori_seinhit_medium"));
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_HSPEED, 7.6);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_PLASMA_SAFE, false);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_FTILT, 1, HG_PROJECTILE_DESTROY_EFFECT, starhit);
