set_attack_value(AT_USTRONG, AG_SPRITE, sprite_get("ustrong"));
set_attack_value(AT_USTRONG, AG_NUM_WINDOWS, 4);
set_attack_value(AT_USTRONG, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_USTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_USTRONG, AG_HURTBOX_SPRITE, sprite_get("ustrong_hurt"));

set_window_value(AT_USTRONG, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_USTRONG, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_USTRONG, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .25);

set_window_value(AT_USTRONG, 2, AG_WINDOW_LENGTH, 26);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .04);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX_FRAME, 7);

set_window_value(AT_USTRONG, 3, AG_WINDOW_LENGTH, 18);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_USTRONG, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, .27);

set_window_value(AT_USTRONG, 4, AG_WINDOW_LENGTH, 13);
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 16);
set_window_value(AT_USTRONG, 4, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 0);

set_num_hitboxes(AT_USTRONG,9);

//mid hitboxes
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 1, HG_LIFETIME, 8);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_Y, -95);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_X, -40);
set_hitbox_value(AT_USTRONG, 1, HG_WIDTH, 50);
set_hitbox_value(AT_USTRONG, 1, HG_HEIGHT, 80);
set_hitbox_value(AT_USTRONG, 1, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 1, HG_DAMAGE, 9);
set_hitbox_value(AT_USTRONG, 1, HG_ANGLE, 95);
set_hitbox_value(AT_USTRONG, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 1, HG_FINAL_BASE_KNOCKBACK, 5.7);
set_hitbox_value(AT_USTRONG, 1, HG_KNOCKBACK_SCALING, .9);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_USTRONG, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_USTRONG, 1, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_USTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_USTRONG, 1, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 2, HG_LIFETIME, 8);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_Y, -95);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_X, 40);
set_hitbox_value(AT_USTRONG, 2, HG_WIDTH, 50);
set_hitbox_value(AT_USTRONG, 2, HG_HEIGHT, 80);
set_hitbox_value(AT_USTRONG, 2, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_USTRONG, 2, HG_ANGLE, 95);
set_hitbox_value(AT_USTRONG, 2, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 2, HG_FINAL_BASE_KNOCKBACK, 5.7);
set_hitbox_value(AT_USTRONG, 2, HG_KNOCKBACK_SCALING, .9);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_USTRONG, 2, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_USTRONG, 2, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_USTRONG, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_USTRONG, 2, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_GROUP, 1);

//sweet spots
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 4, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 4, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_Y, -147);
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_X, 44);
set_hitbox_value(AT_USTRONG, 4, HG_WIDTH, 25);
set_hitbox_value(AT_USTRONG, 4, HG_HEIGHT, 30);
set_hitbox_value(AT_USTRONG, 4, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 4, HG_DAMAGE, 12);
set_hitbox_value(AT_USTRONG, 4, HG_ANGLE, 90);
set_hitbox_value(AT_USTRONG, 4, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_USTRONG, 4, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_USTRONG, 4, HG_FINAL_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG, 4, HG_KNOCKBACK_SCALING, 1.11);
set_hitbox_value(AT_USTRONG, 4, HG_BASE_HITPAUSE, 17);
set_hitbox_value(AT_USTRONG, 4, HG_HITPAUSE_SCALING, .55);
set_hitbox_value(AT_USTRONG, 4, HG_VISUAL_EFFECT_Y_OFFSET, -1);
set_hitbox_value(AT_USTRONG, 4, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 5, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 5, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_Y, -147);
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_X, -44);
set_hitbox_value(AT_USTRONG, 5, HG_WIDTH, 25);
set_hitbox_value(AT_USTRONG, 5, HG_HEIGHT, 30);
set_hitbox_value(AT_USTRONG, 5, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 5, HG_DAMAGE, 12);
set_hitbox_value(AT_USTRONG, 5, HG_ANGLE, 90);
set_hitbox_value(AT_USTRONG, 5, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_USTRONG, 5, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_USTRONG, 5, HG_FINAL_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG, 5, HG_KNOCKBACK_SCALING, 1.11);
set_hitbox_value(AT_USTRONG, 5, HG_BASE_HITPAUSE, 17);
set_hitbox_value(AT_USTRONG, 5, HG_HITPAUSE_SCALING, .55);
set_hitbox_value(AT_USTRONG, 5, HG_VISUAL_EFFECT_Y_OFFSET, -1);
set_hitbox_value(AT_USTRONG, 5, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 5, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_GROUP, 1);

//sour spots
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 6, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 6, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 6, HG_LIFETIME, 8);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_Y, -27);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_X, -41);
set_hitbox_value(AT_USTRONG, 6, HG_WIDTH, 50);
set_hitbox_value(AT_USTRONG, 6, HG_HEIGHT, 62);
set_hitbox_value(AT_USTRONG, 6, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 6, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 6, HG_DAMAGE, 7);
set_hitbox_value(AT_USTRONG, 6, HG_ANGLE, 77);
set_hitbox_value(AT_USTRONG, 6, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 6, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_USTRONG, 6, HG_FINAL_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 6, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_USTRONG, 6, HG_BASE_HITPAUSE, 7.5);
set_hitbox_value(AT_USTRONG, 6, HG_HITPAUSE_SCALING, .45);
set_hitbox_value(AT_USTRONG, 6, HG_VISUAL_EFFECT_Y_OFFSET, -3);
set_hitbox_value(AT_USTRONG, 6, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_USTRONG, 6, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 7, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 7, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_USTRONG, 7, HG_LIFETIME, 8);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_Y, -27);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_X, 41);
set_hitbox_value(AT_USTRONG, 7, HG_WIDTH, 50);
set_hitbox_value(AT_USTRONG, 7, HG_HEIGHT, 62);
set_hitbox_value(AT_USTRONG, 7, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 7, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 7, HG_DAMAGE, 7);
set_hitbox_value(AT_USTRONG, 7, HG_ANGLE, 77);
set_hitbox_value(AT_USTRONG, 7, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 7, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_USTRONG, 7, HG_FINAL_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 7, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_USTRONG, 7, HG_BASE_HITPAUSE, 7.5);
set_hitbox_value(AT_USTRONG, 7, HG_HITPAUSE_SCALING, .45);
set_hitbox_value(AT_USTRONG, 7, HG_VISUAL_EFFECT_Y_OFFSET, -3);
set_hitbox_value(AT_USTRONG, 7, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_USTRONG, 7, HG_VISUAL_EFFECT, empty);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_GROUP, 1);

//SUPER sour spots, when the spikes retreat
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 8, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 8, HG_WINDOW_CREATION_FRAME, 23);
set_hitbox_value(AT_USTRONG, 8, HG_LIFETIME, 3);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_Y, -27);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_X, -40);
set_hitbox_value(AT_USTRONG, 8, HG_WIDTH, 48);
set_hitbox_value(AT_USTRONG, 8, HG_HEIGHT, 60);
set_hitbox_value(AT_USTRONG, 8, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 8, HG_DAMAGE, 4);
set_hitbox_value(AT_USTRONG, 8, HG_ANGLE, -15);
set_hitbox_value(AT_USTRONG, 8, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 8, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 8, HG_KNOCKBACK_SCALING, .1);
set_hitbox_value(AT_USTRONG, 8, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_USTRONG, 8, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_USTRONG, 8, HG_VISUAL_EFFECT_Y_OFFSET, -3);
set_hitbox_value(AT_USTRONG, 8, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_USTRONG, 8, HG_TECHABLE, 3);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_USTRONG, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 9, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 9, HG_WINDOW_CREATION_FRAME, 23);
set_hitbox_value(AT_USTRONG, 9, HG_LIFETIME, 3);
set_hitbox_value(AT_USTRONG, 9, HG_HITBOX_Y, -27);
set_hitbox_value(AT_USTRONG, 9, HG_HITBOX_X, 40);
set_hitbox_value(AT_USTRONG, 9, HG_WIDTH, 48);
set_hitbox_value(AT_USTRONG, 9, HG_HEIGHT, 60);
set_hitbox_value(AT_USTRONG, 9, HG_SHAPE, 2);
set_hitbox_value(AT_USTRONG, 9, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 9, HG_DAMAGE, 4);
set_hitbox_value(AT_USTRONG, 9, HG_ANGLE, -15);
set_hitbox_value(AT_USTRONG, 9, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_USTRONG, 9, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 9, HG_KNOCKBACK_SCALING, .1);
set_hitbox_value(AT_USTRONG, 9, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_USTRONG, 9, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_USTRONG, 9, HG_VISUAL_EFFECT_Y_OFFSET, -3);
set_hitbox_value(AT_USTRONG, 9, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_USTRONG, 9, HG_TECHABLE, 3);
set_hitbox_value(AT_USTRONG, 9, HG_HITBOX_GROUP, 1);


//ending ground-bump hitbox lol
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW, 3);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_USTRONG, 3, HG_LIFETIME, 6);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_Y, -15);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_USTRONG, 3, HG_WIDTH, 60);
set_hitbox_value(AT_USTRONG, 3, HG_HEIGHT, 55);
set_hitbox_value(AT_USTRONG, 3, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_USTRONG, 3, HG_ANGLE, 55);
set_hitbox_value(AT_USTRONG, 3, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_USTRONG, 3, HG_KNOCKBACK_SCALING, .333);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_USTRONG, 3, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_USTRONG, 3, HG_VISUAL_EFFECT_Y_OFFSET, 1);
set_hitbox_value(AT_USTRONG, 3, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_GROUP, 2);
